create or replace external table ET_PC_IMSIGN(
	INITIALCOVERAGESCREATED BOOLEAN AS (CAST(GET($1, 'InitialCoveragesCreated') AS BOOLEAN)),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	SIGNNUMBER NUMBER(38,0) AS (TO_NUMBER(GET($1, 'SignNumber'))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	FIXEDID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'FixedID'))),
	IMSIGNPART NUMBER(38,0) AS (TO_NUMBER(GET($1, 'IMSignPart'))),
	EFFECTIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'EffectiveDate') AS TIMESTAMP_NTZ(9))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	IMLOCATION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'IMLocation'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	EXPIRATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ExpirationDate') AS TIMESTAMP_NTZ(9))),
	INITIALEXCLUSIONSCREATED BOOLEAN AS (CAST(GET($1, 'InitialExclusionsCreated') AS BOOLEAN)),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	ARCHIVEPARTITION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	CHANGETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ChangeType'))),
	INITIALCONDITIONSCREATED BOOLEAN AS (CAST(GET($1, 'InitialConditionsCreated') AS BOOLEAN)),
	BASEDONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BasedOnID'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	INTERIOR BOOLEAN AS (CAST(GET($1, 'interior') AS BOOLEAN)),
	REFERENCEDATEINTERNAL TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ReferenceDateinternal') AS TIMESTAMP_NTZ(9))),
	SIGNTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'SignType'))),
	SUBTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Subtype'))),
	PREFERREDCOVERAGECURRENCY NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PreferredCoverageCurrency'))),
	DESCRIPTION VARCHAR(16777216) AS (CAST(GET($1, 'Description') AS VARCHAR(16777216))),
	BRANCHID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BranchID'))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_IMSIGN_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;