create or replace external table ET_PC_POLICY(
	DONOTPURGE BOOLEAN AS (CAST(GET($1, 'DoNotPurge') AS BOOLEAN)),
	PUBLICID VARCHAR(64) AS (CAST(GET($1, 'PublicID') AS VARCHAR(64))),
	PRIORPREMIUMS NUMBER(9,0) AS (TO_NUMBER(GET($1, 'PriorPremiums'), 9, 0)),
	ISSUEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'IssueDate') AS TIMESTAMP_NTZ(9))),
	PRIORPREMIUMS_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PriorPremiums_cur'))),
	MOVEDPOLICYSOURCEACCOUNTID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'MovedPolicySourceAccountID'), 8, 0)),
	ACCOUNTID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'AccountID'), 8, 0)),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	LOSSHISTORYTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'LossHistoryType'))),
	EXCLUDEDFROMARCHIVE BOOLEAN AS (CAST(GET($1, 'ExcludedFromArchive') AS BOOLEAN)),
	ARCHIVESTATE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ArchiveState'))),
	ARCHIVESCHEMAINFO NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ArchiveSchemaInfo'))),
	ARCHIVEFAILUREDETAILSID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ArchiveFailureDetailsID'), 8, 0)),
	PACKAGERISK NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PackageRisk'))),
	NUMPRIORLOSSES NUMBER(38,0) AS (TO_NUMBER(GET($1, 'NumPriorLosses'))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	PRIMARYLANGUAGE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PrimaryLanguage'))),
	DONOTARCHIVE BOOLEAN AS (CAST(GET($1, 'DoNotArchive') AS BOOLEAN)),
	ID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ID'), 8, 0)),
	PRIMARYLOCALE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PrimaryLocale'))),
	PRODUCTCODE VARCHAR(64) AS (CAST(GET($1, 'ProductCode') AS VARCHAR(64))),
	EXCLUDEREASON VARCHAR(255) AS (CAST(GET($1, 'ExcludeReason') AS VARCHAR(255))),
	CREATEUSERID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'CreateUserID'), 8, 0)),
	ARCHIVEFAILUREID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ArchiveFailureID'), 8, 0)),
	ORIGINALEFFECTIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'OriginalEffectiveDate') AS TIMESTAMP_NTZ(9))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	ARCHIVEPARTITION NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'), 8, 0)),
	RETIRED NUMBER(8,0) AS (TO_NUMBER(GET($1, 'Retired'), 8, 0)),
	UPDATEUSERID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'), 8, 0)),
	PRIORTOTALINCURRED NUMBER(9,0) AS (TO_NUMBER(GET($1, 'PriorTotalIncurred'), 9, 0)),
	ARCHIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ArchiveDate') AS TIMESTAMP_NTZ(9))),
	PRIORTOTALINCURRED_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PriorTotalIncurred_cur'))),
	PRODUCERCODEOFSERVICEID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ProducerCodeOfServiceID'), 8, 0)))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_POLICY_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;