create or replace external table ET_PC_PRODUCERCODE(
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	PRODUCERSTATUS NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ProducerStatus'))),
	PREFERREDUNDERWRITERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PreferredUnderwriterID'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	RETIRED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Retired'))),
	CODEDENORM VARCHAR(16777216) AS (CAST(GET($1, 'CodeDenorm') AS VARCHAR(16777216))),
	CODE VARCHAR(16777216) AS (CAST(GET($1, 'Code') AS VARCHAR(16777216))),
	APPOINTMENTDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'AppointmentDate') AS TIMESTAMP_NTZ(9))),
	ORGANIZATIONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'OrganizationID'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	ADDRESSID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AddressID'))),
	TERMINATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'TerminationDate') AS TIMESTAMP_NTZ(9))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	DESCRIPTIONDENORM VARCHAR(16777216) AS (CAST(GET($1, 'DescriptionDenorm') AS VARCHAR(16777216))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	DESCRIPTION VARCHAR(16777216) AS (CAST(GET($1, 'Description') AS VARCHAR(16777216))),
	BRANCHID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BranchID'))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_PRODUCERCODE_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;