create or replace TABLE YOUR_TABLE_NAME (
	QUERY_ID VARCHAR(16777216),
	STEP_ID NUMBER(38,0),
	OPERATOR_ID NUMBER(38,0),
	PARENT_OPERATORS ARRAY,
	OPERATOR_TYPE VARCHAR(16777216),
	OPERATOR_STATISTICS VARIANT,
	EXECUTION_TIME_BREAKDOWN VARIANT,
	OPERATOR_ATTRIBUTES VARIANT
);