create or replace external table ET_PC_ORGANIZATION(
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	TIER NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Tier'))),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	PRODUCERSTATUS NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ProducerStatus'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	NAMEDENORM VARCHAR(16777216) AS (CAST(GET($1, 'NameDenorm') AS VARCHAR(16777216))),
	RETIRED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Retired'))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	NAME VARCHAR(16777216) AS (CAST(GET($1, 'Name') AS VARCHAR(16777216))),
	NAMEKANJI VARCHAR(16777216) AS (CAST(GET($1, 'NameKanji') AS VARCHAR(16777216))),
	MASTERADMIN NUMBER(38,0) AS (TO_NUMBER(GET($1, 'MasterAdmin'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	CARRIER NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Carrier'))),
	TYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Type'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	CONTACTID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ContactID'))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_ORGANIZATION_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;