create or replace external table ET_PC_ACCOUNTCONTACT(
	CONTACT NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Contact'), 8, 0)),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'), 8, 0)),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(64))),
	ACTIVE BOOLEAN AS (CAST(GET($1, 'Active') AS BOOLEAN)),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	RETIRED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Retired'), 8, 0)),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(8))),
	LASTUPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'LastUpdateTime') AS TIMESTAMP_NTZ(8))),
	ACCOUNT NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Account'), 8, 0)),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'), 8, 0)),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(8))),
	SUBTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Subtype'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'), 8, 0)),
	TEMPORARYLASTUPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'TemporaryLastUpdateTime') AS TIMESTAMP_NTZ(8))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_ACCOUNTCONTACT_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;