create or replace external table ET_PC_PATRANSACTION(
	PUBLICID VARCHAR(64) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	WRITTENDATE TIMESTAMP_NTZ(8) AS (CAST(GET($1, 'WrittenDate') AS TIMESTAMP_NTZ(9))),
	CREATETIME TIMESTAMP_NTZ(8) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	EXPDATE TIMESTAMP_NTZ(8) AS (CAST(GET($1, 'ExpDate') AS TIMESTAMP_NTZ(9))),
	FIXEDID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'FixedID'), 8, 0)),
	EFFDATE TIMESTAMP_NTZ(8) AS (CAST(GET($1, 'EffDate') AS TIMESTAMP_NTZ(9))),
	EFFECTIVEDATE TIMESTAMP_NTZ(8) AS (CAST(GET($1, 'EffectiveDate') AS TIMESTAMP_NTZ(9))),
	UPDATETIME TIMESTAMP_NTZ(8) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	WRITTEN BOOLEAN AS (CAST(GET($1, 'Written') AS BOOLEAN)),
	AMOUNT NUMBER(9,0) AS (TO_NUMBER(GET($1, 'Amount'), 9, 0)),
	AMOUNT_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Amount_cur'))),
	ID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ID'), 8, 0)),
	EXPIRATIONDATE TIMESTAMP_NTZ(8) AS (CAST(GET($1, 'ExpirationDate') AS TIMESTAMP_NTZ(9))),
	CREATEUSERID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'CreateUserID'), 8, 0)),
	AMOUNTBILLING NUMBER(9,0) AS (TO_NUMBER(GET($1, 'AmountBilling'), 9, 0)),
	POLICYFXRATE NUMBER(8,0) AS (TO_NUMBER(GET($1, 'PolicyFXRate'), 8, 0)),
	AMOUNTBILLING_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AmountBilling_cur'))),
	TOBEACCRUED BOOLEAN AS (CAST(GET($1, 'ToBeAccrued') AS BOOLEAN)),
	ARCHIVEPARTITION NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'), 8, 0)),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	CHANGETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ChangeType'))),
	POSTEDDATE TIMESTAMP_NTZ(8) AS (CAST(GET($1, 'PostedDate') AS TIMESTAMP_NTZ(9))),
	BASEDONID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'BasedOnID'), 8, 0)),
	UPDATEUSERID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'), 8, 0)),
	CHARGED BOOLEAN AS (CAST(GET($1, 'Charged') AS BOOLEAN)),
	BRANCHID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'BranchID'), 8, 0)),
	PACOST NUMBER(8,0) AS (TO_NUMBER(GET($1, 'PACost'), 8, 0)))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_PATRANSACTION_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;