create or replace external table ET_PC_GROUP(
	LASTMODIFIED VARCHAR(16777216) AS (SUBSTR(METADATA$FILENAME, 8, 23)),
	SOURCE_FILENAME VARCHAR(16777216) AS (METADATA$FILENAME),
	WORLDVISIBLE BOOLEAN AS (CAST(GET($1, 'WorldVisible') AS BOOLEAN)),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	SUPERVISORID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'SupervisorID'))),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	SECURITYZONEID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'SecurityZoneID'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	NAMEDENORM VARCHAR(16777216) AS (CAST(GET($1, 'NameDenorm') AS VARCHAR(16777216))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTIme') AS TIMESTAMP_NTZ(9))),
	RETIRED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Retired'))),
	VALIDATIONLEVEL NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ValidationLevel'))),
	NAME VARCHAR(16777216) AS (CAST(GET($1, 'Name') AS VARCHAR(16777216))),
	NAMEKANJI VARCHAR(16777216) AS (CAST(GET($1, 'NameKanji') AS VARCHAR(16777216))),
	ORGANIZATIONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'OrganizationID'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	BRANCHCODE VARCHAR(16777216) AS (CAST(GET($1, 'BranchCode') AS VARCHAR(16777216))),
	LOADFACTOR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'LoadFactor'))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	GROUPTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'GroupType'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	DESCRIPTION VARCHAR(16777216) AS (CAST(GET($1, 'Description') AS VARCHAR(16777216))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_GROUP_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;