create or replace external table ET_PC_USER(
	LOADCOMMANDID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'LoadCommandID'))),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	USERTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UserType'))),
	USEPRODUCERCODESECURITY BOOLEAN AS (CAST(GET($1, 'UseProducerCodeSecurity') AS BOOLEAN)),
	USERSETTINGSID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UserSettingsID'))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	SESSIONTIMEOUTSECS NUMBER(38,0) AS (TO_NUMBER(GET($1, 'SessionTimeoutSecs'))),
	ORGANIZATIONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'OrganizationID'))),
	VACATIONSTATUS NUMBER(38,0) AS (TO_NUMBER(GET($1, 'VacationStatus'))),
	DEPARTMENT VARCHAR(16777216) AS (CAST(GET($1, 'Department') AS VARCHAR(16777216))),
	EXTERNALUSER BOOLEAN AS (CAST(GET($1, 'ExternalUser') AS BOOLEAN)),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	USEORGADDRESS BOOLEAN AS (CAST(GET($1, 'UseOrgAddress') AS BOOLEAN)),
	LANGUAGE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Language'))),
	EXPERIENCELEVEL NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ExperienceLevel'))),
	LOCALE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Locale'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	DEFAULTPHONECOUNTRY NUMBER(38,0) AS (TO_NUMBER(GET($1, 'DefaultPhoneCountry'))),
	RETIRED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Retired'))),
	VALIDATIONLEVEL NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ValidationLevel'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	CREDENTIALID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CredentialID'))),
	SYSTEMUSERTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'SystemUserType'))),
	DEFAULTCOUNTRY NUMBER(38,0) AS (TO_NUMBER(GET($1, 'DefaultCountry'))),
	TIMEZONE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'TimeZone'))),
	CONTACTID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ContactID'))),
	JOBTITLE VARCHAR(16777216) AS (CAST(GET($1, 'JobTitle') AS VARCHAR(16777216))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_USER_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;