create or replace external table ET_PC_PERSONALVEHICLECOV(
	CHOICETERM1 VARCHAR(64) AS (CAST(GET($1, 'ChoiceTerm1') AS VARCHAR(64))),
	PUBLICID VARCHAR(64) AS (CAST(GET($1, 'PublicID') AS VARCHAR(64))),
	CHOICETERM2 VARCHAR(64) AS (CAST(GET($1, 'ChoiceTerm2') AS VARCHAR(64))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	FIXEDID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'FixedID'), 8, 0)),
	CURRENCY NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Currency'))),
	CHOICETERM1AVL BOOLEAN AS (CAST(GET($1, 'ChoiceTerm1Avl') AS BOOLEAN)),
	EFFECTIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'EffectiveDate') AS TIMESTAMP_NTZ(9))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	BOOLEANTERM1AVL BOOLEAN AS (CAST(GET($1, 'BooleanTerm1Avl') AS BOOLEAN)),
	ID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ID'), 8, 0)),
	BOOLEANTERM1 BOOLEAN AS (CAST(GET($1, 'BooleanTerm1') AS BOOLEAN)),
	EXPIRATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ExpirationDate') AS TIMESTAMP_NTZ(9))),
	CREATEUSERID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'CreateUserID'), 8, 0)),
	ARCHIVEPARTITION NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'), 8, 0)),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	CHANGETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ChangeType'))),
	PERSONALVEHICLE NUMBER(8,0) AS (TO_NUMBER(GET($1, 'PersonalVehicle'), 8, 0)),
	BASEDONID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'BasedOnID'), 8, 0)),
	UPDATEUSERID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'), 8, 0)),
	CHOICETERM2AVL BOOLEAN AS (CAST(GET($1, 'ChoiceTerm2Avl') AS BOOLEAN)),
	REFERENCEDATEINTERNAL TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ReferenceDateInternal') AS TIMESTAMP_NTZ(9))),
	SUBTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Subtype'))),
	PATTERNCODE VARCHAR(64) AS (CAST(GET($1, 'PatternCode') AS VARCHAR(64))),
	BRANCHID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'BranchID'), 8, 0)))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_PERSONALVEHICLECOV_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;