create or replace external table ET_PC_CPBUILDING(
	INITIALCOVERAGESCREATED BOOLEAN AS (CAST(GET($1, 'InitialCoveragesCreated') AS BOOLEAN)),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	FIXEDID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'FixedID'))),
	EFFECTIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'EffectiveDate') AS TIMESTAMP_NTZ(9))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	RATETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'RateType'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	EXPIRATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ExpirationDate') AS TIMESTAMP_NTZ(9))),
	INITIALEXCLUSIONSCREATED BOOLEAN AS (CAST(GET($1, 'InitialExclusionsCreated') AS BOOLEAN)),
	CPLOCATION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CPLocation'))),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	CLASSCODE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ClassCode'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	ARCHIVEPARTITION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'))),
	CHANGETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ChangeType'))),
	INITIALCONDITIONSCREATED BOOLEAN AS (CAST(GET($1, 'InitialConditionsCreated') AS BOOLEAN)),
	COVERAGEFORM NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CoverageForm'))),
	BASEDONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BasedOnID'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	BUILDING NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Building'))),
	REFERENCEDATEINTERNAL TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ReferenceDateInternal') AS TIMESTAMP_NTZ(9))),
	PREFERREDCOVERAGECURRENCY NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PreferredCoverageCurrency'))),
	BRANCHID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BranchID'))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_CPBUILDING_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;