create or replace external table ET_PC_ACCOUNT(
	FILE_TIMESTAMP VARCHAR(16777216) AS (SUBSTR(METADATA$FILENAME, 16, 23)),
	SOURCE_FILENAME VARCHAR(16777216) AS (METADATA$FILENAME),
	BUSOPSDESC VARCHAR(16777216) AS (CAST(GET($1, 'BusOpsDesc') AS VARCHAR(240))),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(64))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(8))),
	LINKCONTACTS BOOLEAN AS (CAST(GET($1, 'LinkContacts') AS BOOLEAN)),
	ACCOUNTORGTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AccountOrgType'))),
	LOCATIONAUTONUMBERSEQ NUMBER(38,0) AS (TO_NUMBER(GET($1, 'LocationAutoNumberSeq'), 8, 0)),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(8))),
	SERVICETIER NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ServiceTier'))),
	PRIMARYLANGUAGE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PrimaryLanguage'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'), 8, 0)),
	STATEBUREAUNUM VARCHAR(16777216) AS (CAST(GET($1, 'StateBureauNum') AS VARCHAR(255))),
	PRIMARYLOCALE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PrimaryLocale'))),
	ACCOUNTSTATUS NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AccountStatus'))),
	FROZEN BOOLEAN AS (CAST(GET($1, 'Frozen') AS BOOLEAN)),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'), 8, 0)),
	YEARBUSINESSSTARTED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'YearBusinessStarted'))),
	INDUSTRYCODEID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'IndustryCodeID'), 8, 0)),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	RETIRED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Retired'), 8, 0)),
	LOCKINGCOLUMN NUMBER(38,0) AS (TO_NUMBER(GET($1, 'LockingColumn'))),
	OTHERORGTYPEDESCRIPTION VARCHAR(16777216) AS (CAST(GET($1, 'OtherOrgTypeDescription') AS VARCHAR(40))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'), 8, 0)),
	ACCOUNTNUMBERDENORM VARCHAR(16777216) AS (CAST(GET($1, 'AccountNumberDenorm') AS VARCHAR(255))),
	ACCOUNTNUMBER VARCHAR(16777216) AS (CAST(GET($1, 'AccountNumber') AS VARCHAR(255))),
	PREFERREDCOVERAGECURRENCY NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PreferredCoverageCurrency'))),
	PREFERREDSETTLEMENTCURRENCY NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PreferredSettlementCurrency'))),
	ORIGINATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'OriginationDate') AS TIMESTAMP_NTZ(8))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_ACCOUNT_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;