create or replace external table ET_PC_EFFECTIVEDATEDFIELDS(
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	POLICYADDRESS NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PolicyAddress'))),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	SECONDARYNAMEDINSURED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'SecondaryNamedInsured'))),
	BILLINGCONTACT NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BillingContact'))),
	ARCHIVEPARTITION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	CHANGETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ChangeType'))),
	BASEDONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BasedOnID'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	FIXEDID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'FixedID'))),
	OFFERINGCODE VARCHAR(16777216) AS (CAST(GET($1, 'OfferingCode') AS VARCHAR(16777216))),
	PRIMARYNAMEDINSURED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PrimaryNamedInsured'))),
	EFFECTIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'EffectiveDate') AS TIMESTAMP_NTZ(9))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	PRIMARYLOCATION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PrimaryLocation'))),
	PRODUCERCODEID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ProducerCodeID'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	BRANCHID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BranchID'))),
	EXPIRATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ExpirationDate') AS TIMESTAMP_NTZ(9))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_EFFECTIVEDATEDFIELDS_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;