create or replace TABLE RAW_CONTROL_TABLE (
	CONTROL_ID NUMBER(38,0) NOT NULL autoincrement,
	SNOWFLAKE_WORSKPACE VARCHAR(255),
	SERVER_NAME VARCHAR(255),
	DATABASE_NAME VARCHAR(255),
	SCHEMA_NAME VARCHAR(255),
	TABLE_NAME VARCHAR(255) NOT NULL,
	ETL_VELOCITY VARCHAR(255),
	CURRENT_VALUE VARCHAR(255),
	PREVIOUS_VALUE VARCHAR(255),
	IS_INCREMENTAL_LOAD BOOLEAN,
	EDW_CREATED_DATE TIMESTAMP_NTZ(9),
	EDW_CREATED_BY VARCHAR(255),
	EDW_MODIFIED_DATE TIMESTAMP_NTZ(9),
	EDW_MODIFIED_BY VARCHAR(255),
	DATALAKE_CONTAINER VARCHAR(255),
	DATALAKE_FOLDER VARCHAR(255),
	DISABLE_LOAD_FLAG BOOLEAN,
	CDC_COLUMN_NAME VARCHAR(100),
	primary key (CONTROL_ID)
)COMMENT='Adding column - CDC_COLUMN_NAME'
;