create or replace external table ET_PC_AUDITINFORMATION(
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(64))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(8))),
	AUDITFEE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AuditFee'), 9, 0)),
	AUDITFEE_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AuditFee_cur'))),
	POLICYID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PolicyID'), 8, 0)),
	WAIVE BOOLEAN AS (CAST(GET($1, 'Waive') AS BOOLEAN)),
	RECEIVEDDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ReceivedDate') AS TIMESTAMP_NTZ(8))),
	REVISIONTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'RevisionType'))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(8))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'), 8, 0)),
	DUEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'DueDate') AS TIMESTAMP_NTZ(8))),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'), 8, 0)),
	INSTRUCTIONS VARCHAR(16777216) AS (CAST(GET($1, 'Instructions') AS VARCHAR(2))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	RETIRED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Retired'), 8, 0)),
	AUDITSCHEDULETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AuditScheduleType'))),
	AUDITPERIODENDDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'AuditPeriodEndDate') AS TIMESTAMP_NTZ(8))),
	ACTUALAUDITMETHOD NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ActualAuditMethod'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'), 8, 0)),
	ESCALATED BOOLEAN AS (CAST(GET($1, 'Escalated') AS BOOLEAN)),
	AUDITPERIODSTARTDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'AuditPeriodStartDate') AS TIMESTAMP_NTZ(8))),
	SERIES BOOLEAN AS (CAST(GET($1, 'Series') AS BOOLEAN)),
	POLICYTERMID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PolicyTermID'), 8, 0)),
	REVERSALDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ReversalDate') AS TIMESTAMP_NTZ(8))),
	AUDITMETHOD NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AuditMethod'))),
	INITDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'InitDate') AS TIMESTAMP_NTZ(8))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_AUDITINFORMATION_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;