create or replace external table ET_PC_GLTRANSACTION(
	FILE_TIMESTAMP VARCHAR(16777216) AS (SUBSTR(METADATA$FILENAME, 24, 23)),
	SOURCE_FILENAME VARCHAR(16777216) AS (METADATA$FILENAME),
	PUBLICID VARCHAR(64) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	WRITTENDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'WrittenDate') AS TIMESTAMP_NTZ(9))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	EXPDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ExpDate') AS TIMESTAMP_NTZ(9))),
	FIXEDID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'FixedID'))),
	EFFDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'EffDate') AS TIMESTAMP_NTZ(9))),
	EFFECTIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'EffectiveDate') AS TIMESTAMP_NTZ(9))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	WRITTEN BOOLEAN AS (CAST(GET($1, 'Written') AS BOOLEAN)),
	AMOUNT NUMBER(9,0) AS (TO_NUMBER(GET($1, 'Amount'))),
	AMOUNT_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Amount_cur'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	EXPIRATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ExpirationDate') AS TIMESTAMP_NTZ(9))),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	AMOUNTBILLING NUMBER(9,0) AS (TO_NUMBER(GET($1, 'AmountBilling'))),
	POLICYFXRATE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PolicyFXRate'))),
	AMOUNTBILLING_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AmountBilling_cur'))),
	TOBEACCRUED BOOLEAN AS (CAST(GET($1, 'ToBeAccrued') AS BOOLEAN)),
	ARCHIVEPARTITION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	CHANGETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ChangeType'))),
	POSTEDDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'PostedDate') AS TIMESTAMP_NTZ(9))),
	BASEDONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BasedOnID'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	CHARGED BOOLEAN AS (CAST(GET($1, 'Charged') AS BOOLEAN)),
	GLCOST NUMBER(38,0) AS (TO_NUMBER(GET($1, 'GLCost'))),
	BRANCHID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BranchID'))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_GLTRANSACTION_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;