create or replace external table ET_PC_GLEXPOSURE(
	FILE_TIMESTAMP VARCHAR(16777216) AS (SUBSTR(METADATA$FILENAME, 24, 23)),
	SOURCE_FILENAME VARCHAR(16777216) AS (METADATA$FILENAME),
	CLASSCODEID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ClassCodeID'))),
	SCALABLEBASISAMOUNT NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ScalableBasisAmount'))),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	FIXEDBASISAMOUNT NUMBER(38,0) AS (TO_NUMBER(GET($1, 'FixedBasisAmount'))),
	PUBLICID VARCHAR(64) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	AUDITEDBASIS NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AuditedBasis'))),
	ARCHIVEPARTITION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	CHANGETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ChangeType'))),
	BASEDONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BasedOnID'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	FIXEDID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'FixedID'))),
	LOCATION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Location'))),
	EFFECTIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'EffectiveDate') AS TIMESTAMP_NTZ(9))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	GLLINE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'GLLine'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	DESCRIPTION VARCHAR(255) AS (CAST(GET($1, 'Description') AS VARCHAR(16777216))),
	BRANCHID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BranchID'))),
	EXPIRATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ExpirationDate') AS TIMESTAMP_NTZ(9))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_GLEXPOSURE_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;