create or replace external table ET_PC_POLICYTERM(
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	MOSTRECENTTERM BOOLEAN AS (CAST(GET($1, 'MostRecentTerm') AS BOOLEAN)),
	POLICYID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PolicyID'))),
	GENERATEREINSURABLES BOOLEAN AS (CAST(GET($1, 'GenerateReinsurables') AS BOOLEAN)),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	FINALAUDITOPTION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'FinalAuditOption'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	DEPOSITRELEASED BOOLEAN AS (CAST(GET($1, 'DepositReleased') AS BOOLEAN)),
	TOTALESTIMATEDPREMIUM NUMBER(38,0) AS (TO_NUMBER(GET($1, 'TotalEstimatedPremium'))),
	TOTALESTIMATEDPREMIUM_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'TotalEstimatedPremium_cur'))),
	TOTALREPORTEDPREMIUM NUMBER(38,0) AS (TO_NUMBER(GET($1, 'TotalReportedPremium'))),
	TOTALREPORTEDPREMIUM_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'TotalReportedPremium_cur'))),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	NONRENEWREASON NUMBER(38,0) AS (TO_NUMBER(GET($1, 'NonRenewReason'))),
	LASTRESTOREDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'LastRestoreDate') AS TIMESTAMP_NTZ(9))),
	NEXTARCHIVECHECKDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'NextArchiveCheckDate') AS TIMESTAMP_NTZ(9))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	RETIRED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Retired'))),
	PRERENEWALDIRECTION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PreRenewalDirection'))),
	DAYSREPORTED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'DaysReported'))),
	POLICYTERMARCHIVESTATE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PolicyTermArchiveState'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	NEXTRENEWALCHECKDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'NextRenewalCheckDate') AS TIMESTAMP_NTZ(9))),
	AFFINITYGROUPID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'AffinityGroupID'))),
	DEPOSITAMOUNT NUMBER(38,0) AS (TO_NUMBER(GET($1, 'DepositAmount'))),
	DEPOSITAMOUNT_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'DepositAmount_cur'))),
	NONRENEWADDEXPLANATION VARCHAR(16777216) AS (CAST(GET($1, 'NonRenewAddExplanation') AS VARCHAR(16777216))),
	BOUND BOOLEAN AS (CAST(GET($1, 'Bound') AS BOOLEAN)))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_POLICYTERM_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;