create or replace external table ET_PC_UWISSUE(
	LONGDESCRIPTION VARCHAR(16777216) AS (CAST(GET($1, 'LongDescription') AS VARCHAR(16777216))),
	SHORTDESCRIPTION VARCHAR(16777216) AS (CAST(GET($1, 'ShortDescription') AS VARCHAR(16777216))),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	ACTIVE BOOLEAN AS (CAST(GET($1, 'Active') AS BOOLEAN)),
	HASAPPROVALORREJECTION BOOLEAN AS (CAST(GET($1, 'HasApprovalOrRejection') AS BOOLEAN)),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	APPROVALVALUE VARCHAR(16777216) AS (CAST(GET($1, 'ApprovalValue') AS VARCHAR(16777216))),
	FIXEDID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'FixedID'))),
	APPROVALDURATIONTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ApprovalDurationType'))),
	APPROVINGUSER NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ApprovalDurationType'))),
	EFFECTIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'EffectiveDate') AS TIMESTAMP_NTZ(9))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	APPROVALBLOCKINGPOINT NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ApprovalBlockingPoint'))),
	CANEDITAPPROVALBEFOREBIND BOOLEAN AS (CAST(GET($1, 'CanEditApprovalBeforeBind') AS BOOLEAN)),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	EXPIRATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ExpirationDate') AS TIMESTAMP_NTZ(9))),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	ISSUEKEY VARCHAR(16777216) AS (CAST(GET($1, 'IssueKey') AS VARCHAR(16777216))),
	ARCHIVEPARTITION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	CHANGETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ChangeType'))),
	BASEDONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BasedOnID'))),
	ISSUETYPEID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'IssueTypeID'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	VALVE VARCHAR(16777216) AS (CAST(GET($1, 'VALUE') AS VARCHAR(16777216))),
	AUTOMATICAPPROVALCAUSE VARCHAR(16777216) AS (CAST(GET($1, 'AutomaticApprovalCause') AS VARCHAR(16777216))),
	BRANCHID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BranchID'))),
	APPROVALINVALIDFROM TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ApprovalInvalidFrom') AS TIMESTAMP_NTZ(9))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_UWISSUE_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;