create or replace external table ET_PC_BOPBUILDING(
	CLASSCODEID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ClassCodeID'))),
	INITIALCOVERAGESCREATED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'InitialCoveragesCreated'))),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	CREATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(8))),
	CONSTRUCTIONTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ConstructionType'))),
	FIXEDID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'FixedID'))),
	NUMPOOLS NUMBER(38,0) AS (TO_NUMBER(GET($1, 'NumPools'))),
	EFFECTIVEDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'EffectiveDate') AS TIMESTAMP_NTZ(8))),
	BASISAMOUNT NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BasisAmount'))),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(8))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))),
	EXPIRATIONDATE TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ExpirationDate') AS TIMESTAMP_NTZ(8))),
	INITIALEXCLUSIONSCREATED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'InitialExclusionsCreated'))),
	CREATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'CreateUserID'))),
	ARCHIVEPARTITION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	CHANGETYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ChangeType'))),
	INITIALCONDITIONSCREATED NUMBER(38,0) AS (TO_NUMBER(GET($1, 'InitialConditionsCreated'))),
	BASEDONID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BasedOnID'))),
	UPDATEUSERID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'))),
	BUILDING NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Building'))),
	REFERENCEDATEINTERNAL TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'ReferenceDateInternal') AS TIMESTAMP_NTZ(8))),
	NUMDIVING NUMBER(38,0) AS (TO_NUMBER(GET($1, 'NumDiving'))),
	BOPLOCATION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BOPLocation'))),
	PREFERREDCOVERAGECURRENCY NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PreferredCoverageCurrency'))),
	BRANCHID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BranchID'))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_BOPBUILDING_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;