create or replace external table ET_PC_GROUPPRODUCERCODE(
	LASTMODIFIED VARCHAR(16777216) AS (SUBSTR(METADATA$FILENAME, 20, 23)),
	SOURCE_FILENAME VARCHAR(16777216) AS (METADATA$FILENAME),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	PRODUCERCODEID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ProducerCodeID'))),
	GROUPID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ProducerCodeID'))),
	ID NUMBER(38,0) AS (TO_NUMBER(GET($1, 'ID'))))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_GROUPPRODUCERCODE_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;