create or replace external table ET_PC_PAYMENTPLANSUMMARY(
	NOTES VARCHAR(16777216) AS (CAST(GET($1, 'Notes') AS VARCHAR(16777216))),
	CREATEUSERID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'CreateUserID'), 8, 0)),
	PUBLICID VARCHAR(16777216) AS (CAST(GET($1, 'PublicID') AS VARCHAR(16777216))),
	DOWNPAYMENT NUMBER(9,0) AS (TO_NUMBER(GET($1, 'DownPayment'))),
	TOTAL NUMBER(9,0) AS (TO_NUMBER(GET($1, 'Total'))),
	TOTAL_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Total_cur'))),
	DOWNPAYMENT_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'DownPayment_cur'))),
	BEANVERSION NUMBER(38,0) AS (TO_NUMBER(GET($1, 'BeanVersion'))),
	ARCHIVEPARTITION NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ArchivePartition'), 8, 0)),
	CREATETIME TIMESTAMP_NTZ(8) AS (CAST(GET($1, 'CreateTime') AS TIMESTAMP_NTZ(9))),
	RETIRED NUMBER(8,0) AS (TO_NUMBER(GET($1, 'Retired'), 8, 0)),
	PAYMENTPLANTYPE NUMBER(38,0) AS (TO_NUMBER(GET($1, 'PaymentPlanType'))),
	NAME VARCHAR(255) AS (CAST(GET($1, 'Name') AS VARCHAR(255))),
	UPDATEUSERID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'UpdateUserID'), 8, 0)),
	INVOICEFREQUENCY NUMBER(38,0) AS (TO_NUMBER(GET($1, 'InvoiceFrequency'))),
	REPORTINGPATTERNCODE VARCHAR(64) AS (CAST(GET($1, 'ReportingPatternCode') AS VARCHAR(64))),
	POLICYPERIOD NUMBER(8,0) AS (TO_NUMBER(GET($1, 'PolicyPeriod'), 8, 0)),
	UPDATETIME TIMESTAMP_NTZ(9) AS (CAST(GET($1, 'UpdateTime') AS TIMESTAMP_NTZ(9))),
	BILLINGID VARCHAR(255) AS (CAST(GET($1, 'BillingId') AS VARCHAR(255))),
	INSTALLMENT NUMBER(9,0) AS (TO_NUMBER(GET($1, 'Installment'), 9, 0)),
	INSTALLMENT_CUR NUMBER(38,0) AS (TO_NUMBER(GET($1, 'Installment_cur'))),
	ID NUMBER(8,0) AS (TO_NUMBER(GET($1, 'ID'), 8, 0)))
location=@CSVLOADING/
auto_refresh=false
pattern='.*dbo_PC_PAYMENTPLANSUMMARY_.*'
file_format=(TYPE=PARQUET NULL_IF=())
;