create or replace TABLE USER_DETAILS_2334 (
	USER_ID NUMBER(38,0),
	USERNAME VARCHAR(255),
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	GENDER VARCHAR(10),
	PASSWORD VARCHAR(50),
	STATUS VARCHAR(50)
);