create or replace view V_POL_TRN_ALL_STG(
	ID,
	TRANSACTION_PRO_DATE,
	TRANSACTION_TYPE_CODE,
	TRANSACTION_CODE,
	WRITTEN_PREMIUM_AMT,
	CHARGE_TYPECODE,
	TOTALPREMIUMRPT,
	TOTALREPORTEDPREMIUM,
	PCTL_TYPECODE,
	TAX_AMOUNT,
	FEE_AMOUNT,
	SURCHARGE_AMOUNT,
	PREM_BASIS_AMT,
	AMOUNT,
	ACTUALAMOUNT,
	TRANSACTION_AMOUNT,
	ACCTG_PRD_ID,
	TRANS_EFF_DATE,
	TRANS_EXP_DATE,
	RISK_TYPE_CODE,
	PREM_FULLY_EARNED_FL,
	CURRENCY_CODE,
	INFORCE_PREM_AMOUNT
) as 
    SELECT * FROM BA_STG_VW
    UNION ALL
    SELECT * FROM BOP_STG_VW
    UNION ALL
    SELECT * FROM CP_STG_VW
    UNION ALL
    SELECT * FROM GL_STG_VW
    UNION ALL
    SELECT * FROM IM_STG_VW
    UNION ALL
    SELECT * FROM PA_STG_VW
    UNION ALL
    SELECT * FROM WC_STG_VW;