create or replace view BOP_STG_VW(
	ID,
	TRANSACTION_PRO_DATE,
	TRANSACTION_TYPE_CODE,
	TRANSACTION_CODE,
	WRITTEN_PREMIUM_AMT,
	CHARGE_TYPECODE,
	TOTALPREMIUMRPT,
	TOTALREPORTEDPREMIUM,
	PCTL_TYPECODE,
	TAX_AMOUNT,
	FEE_AMOUNT,
	SURCHARGE_AMOUNT,
	PREM_BASIS_AMT,
	AMOUNT,
	ACTUALAMOUNT,
	TRANSACTION_AMOUNT,
	ACCTG_PRD_ID,
	TRANS_EFF_DATE,
	TRANS_EXP_DATE,
	RISK_TYPE_CODE,
	PREM_FULLY_EARNED_FL,
	CURRENCY_CODE,
	INFORCE_PREM_AMOUNT
) as
WITH CTE_TRANSACTION_TYPE_CODE (TRANSACTION_TYPE_CODE,PC_BOPCOST_ID) AS
--CALCULATION OF TRANSACTION_TYPE_CODE
(SELECT dl_pc_ext.ET_pctl_bopcost.TYPECODE as TRANSACTION_TYPE_CODE,dl_pc_ext.et_pc_BOPCOST.ID AS PC_BOPCOST_ID
from dl_pc_ext.ET_pctl_bopcost left outer join dl_pc_ext.et_pc_BOPCOST
on dl_pc_ext.ET_pctl_bopcost.id = dl_pc_ext.et_pc_BOPCOST.SUBTYPE),

CTE_TRANSACTION_CODE (TRANSACTION_CODE,PC_JOB_ID) AS
--CALCULATION OF TRANSACTION_CODE
(select dl_pc_ext.et_pctl_job.TYPECODE as TRANSACTION_CODE, dl_pc_ext.et_pc_JOB.ID AS PC_JOB_ID
from dl_pc_ext.et_pctl_job left outer join dl_pc_ext.et_pc_JOB 
on dl_pc_ext.et_pctl_job.id = dl_pc_ext.et_pc_JOB.SUBTYPE),

CTE_CHARGE_TYPECODE(CHARGE_TYPECODE,PC_BOPCOST_ID) AS
--CALCULATION OF CHARGE_TYPECODE
(select  dl_pc_ext.et_pctl_chargepattern.TYPECODE as CHARGE_TYPECODE,dl_pc_ext.et_pc_BOPCOST.ID AS PC_BOPCOST_ID
from dl_pc_ext.et_pctl_chargepattern left outer join dl_pc_ext.et_pc_BOPCOST
on dl_pc_ext.et_pctl_chargepattern.id = dl_pc_ext.et_pc_BOPCOST.CHARGEPATTERN),

CTE_CURRENCY_CODE (CURRENCY_CODE,PC_BOPTRANSACTION_ID) AS
--CALCULATION OF CTE_CURRENCY_CODE
(SELECT dl_pc_ext.et_pctl_currency.TYPECODE AS CURRENCY_CODE,dl_pc_ext.et_PC_BOPTRANSACTION.ID AS PC_BOPTRANSACTION_ID
FROM dl_pc_ext.et_pctl_currency LEFT OUTER JOIN dl_pc_ext.et_PC_BOPTRANSACTION
ON dl_pc_ext.et_pctl_currency.ID = dl_pc_ext.et_PC_BOPTRANSACTION.AMOUNT_CUR),

CTE_PCTL_TYPECODE (PCTL_TYPECODE,PC_POLICYPERIOD_ID) AS
--CALCULATION OF PCTL_TYPECODE
(SELECT dl_pc_ext.et_pctl_policyperiodstatus.TYPECODE as PCTL_TYPECODE,dl_pc_ext.et_pc_POLICYPERIOD.ID AS PC_POLICYPERIOD_ID
FROM dl_pc_ext.et_pctl_policyperiodstatus LEFT OUTER JOIN dl_pc_ext.et_pc_POLICYPERIOD
ON dl_pc_ext.et_pctl_policyperiodstatus.ID = dl_pc_ext.et_pc_POLICYPERIOD.STATUS)

SELECT 
dl_pc_ext.et_pc_BOPTRANSACTION.ID AS ID,
cast(dl_pc_ext.et_pc_JOB.CLOSEDATE AS DATETIME) as TRANSACTION_PRO_DATE,
TRANSACTION_TYPE_CODE, 
TRANSACTION_CODE,
CASE WHEN (CTE_CHARGE_TYPECODE.CHARGE_TYPECODE='Premium' AND dl_pc_ext.et_PC_BOPTRANSACTION.CHARGED=1) THEN dl_pc_ext.et_PC_BOPTRANSACTION.AMOUNT ELSE 0
END AS WRITTEN_PREMIUM_AMT,
CHARGE_TYPECODE,
dl_pc_ext.et_pc_POLICYPERIOD.TOTALPREMIUMRPT AS TOTALPREMIUMRPT,
dl_pc_ext.et_pc_POLICYTERM.TOTALREPORTEDPREMIUM AS TOTALREPORTEDPREMIUM,
PCTL_TYPECODE,
CASE WHEN (CTE_CHARGE_TYPECODE.CHARGE_TYPECODE = 'Taxes') THEN dl_pc_ext.et_PC_BOPTRANSACTION.AMOUNT ELSE 0 END AS TAX_AMOUNT,
CASE WHEN(CTE_CHARGE_TYPECODE.CHARGE_TYPECODE='InstallmentFee' OR CTE_CHARGE_TYPECODE.CHARGE_TYPECODE='ReinstatementFee') THEN
dl_pc_ext.et_PC_BOPTRANSACTION.AMOUNT ELSE 0 END AS FEE_AMOUNT,
CASE WHEN (CTE_CHARGE_TYPECODE.CHARGE_TYPECODE='Surcharges') THEN dl_pc_ext.et_PC_BOPTRANSACTION.AMOUNT ELSE 0 END AS SURCHARGE_AMOUNT,
CAST(dl_pc_ext.et_pc_BOPCOST.BASIS AS DECIMAL) AS PREM_BASIS_AMT,
CAST(dl_pc_ext.et_PC_BOPTRANSACTION.AMOUNT AS DECIMAL) AS AMOUNT,
CAST(dl_pc_ext.et_pc_BOPCOST.ACTUALAMOUNT AS DECIMAL) AS ACTUALAMOUNT,
dl_pc_ext.et_PC_BOPTRANSACTION.AMOUNT as TRANSACTION_AMOUNT,
TO_CHAR(DL_PC_EXT.et_PC_BOPTRANSACTION.WRITTENDATE,'MMYYYY')::NUMBER AS ACCTG_PRD_ID,
CAST(dl_pc_ext.et_PC_BOPTRANSACTION.EFFDATE AS DATETIME) AS TRANS_EFF_DATE,
cast(dl_pc_ext.et_PC_BOPTRANSACTION.EXPDATE AS DATETIME) AS TRANS_EXP_DATE,
'BA' AS RISK_TYPE_CODE,
CASE WHEN (dl_pc_ext.et_PC_BOPTRANSACTION.Written = 1 AND dl_pc_ext.et_PC_BOPTRANSACTION.TOBEACCRUED =1) THEN 'Y' ELSE 'N' END AS PREM_FULLY_EARNED_FL,
CURRENCY_CODE,
CASE WHEN (CTE_CHARGE_TYPECODE.CHARGE_TYPECODE='Premium' AND dl_pc_ext.et_PC_BOPTRANSACTION.CHARGED=1 )THEN dl_pc_ext.et_PC_BOPTRANSACTION.AMOUNT ELSE 0 END AS INFORCE_PREM_AMOUNT
FROM DL_PC_EXT.et_PC_BOPTRANSACTION
LEFT OUTER JOIN DL_PC_EXT.ET_PC_BOPCOST
ON DL_PC_EXT.et_PC_BOPTRANSACTION.BOPCOST  = DL_PC_EXT.ET_PC_BOPCOST.ID
LEFT OUTER JOIN DL_PC_EXT.ET_PC_POLICYPERIOD
ON DL_PC_EXT.ET_pc_boptransaction.BRANCHID = DL_PC_EXT.ET_PC_POLICYPERIOD.ID
LEFT OUTER JOIN DL_PC_EXT.ET_PC_BOPBUILDINGCOV ON 
DL_PC_EXT.ET_PC_BOPCOST.BRANCHID = DL_PC_EXT.ET_PC_BOPBUILDINGCOV.BRANCHID AND
DL_PC_EXT.ET_PC_BOPCOST.BOPBUILDINGCOV =DL_PC_EXT.ET_PC_BOPBUILDINGCOV.FIXEDID AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE >= COALESCE (DL_PC_EXT.ET_PC_BOPBUILDINGCOV.EFFECTIVEDATE,
 DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODSTART) AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE < COALESCE (DL_PC_EXT.ET_PC_BOPBUILDINGCOV.EXPIRATIONDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODEND)
LEFT OUTER JOIN  DL_PC_EXT.ET_PC_BOPBUILDING ON
DL_PC_EXT.ET_PC_BOPBUILDINGCOV.BRANCHID = DL_PC_EXT.ET_PC_BOPBUILDING.BRANCHID AND
DL_PC_EXT.ET_PC_BOPBUILDINGCOV.BOPBuilding = DL_PC_EXT.ET_PC_BOPBUILDING.FixedID AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE >= COALESCE(DL_PC_EXT.ET_PC_BOPBUILDING.EFFECTIVEDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODSTART) AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE < COALESCE(DL_PC_EXT.ET_PC_BOPBUILDING.EXPIRATIONDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODEND)
LEFT OUTER JOIN DL_PC_EXT.ET_PC_BUILDING ON
DL_PC_EXT.ET_PC_BOPBUILDING.BRANCHID = DL_PC_EXT.ET_PC_BUILDING.BRANCHID and 
DL_PC_EXT.ET_PC_BOPBUILDING.BUILDING = DL_PC_EXT.ET_PC_BUILDING.FIXEDID and
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE >= COALESCE(DL_PC_EXT.ET_PC_BUILDING.EFFECTIVEDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODSTART) and
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE < COALESCE(DL_PC_EXT.ET_PC_BUILDING.EXPIRATIONDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODEND) 
LEFT OUTER JOIN DL_PC_EXT.ET_pc_policylocation ON  
DL_PC_EXT.ET_PC_BUILDING.BRANCHID = DL_PC_EXT.ET_PC_POLICYLOCATION.BRANCHID AND
DL_PC_EXT.ET_PC_BUILDING.POLICYLOCATION  = DL_PC_EXT.ET_PC_POLICYLOCATION.FIXEDID AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE >= COALESCE(DL_PC_EXT.ET_PC_POLICYLOCATION.EFFECTIVEDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODSTART) AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE < COALESCE(DL_PC_EXT.ET_PC_POLICYLOCATION.EXPIRATIONDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODEND)
LEFT OUTER JOIN DL_PC_EXT.ET_PC_EFFECTIVEDATEDFIELDS ON
DL_PC_EXT.ET_PC_BOPCOST.BRANCHID = DL_PC_EXT.ET_PC_EFFECTIVEDATEDFIELDS.BRANCHID AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE >= COALESCE(DL_PC_EXT.ET_PC_EFFECTIVEDATEDFIELDS.EFFECTIVEDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODSTART) AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE < COALESCE(DL_PC_EXT.ET_PC_EFFECTIVEDATEDFIELDS.EXPIRATIONDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODEND)
LEFT OUTER JOIN DL_PC_EXT.ET_PC_POLICYLOCATION AS PC_POLICYLOCATION_1 ON
DL_PC_EXT.ET_PC_EFFECTIVEDATEDFIELDS.BRANCHID = PC_POLICYLOCATION_1.BRANCHID AND
DL_PC_EXT.ET_PC_EFFECTIVEDATEDFIELDS.PRIMARYLOCATION = PC_POLICYLOCATION_1.FIXEDID AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE >= COALESCE(PC_POLICYLOCATION_1.EFFECTIVEDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODSTART) AND
DL_PC_EXT.ET_PC_POLICYPERIOD.EDITEFFECTIVEDATE < COALESCE(PC_POLICYLOCATION_1.EXPIRATIONDATE, DL_PC_EXT.ET_PC_POLICYPERIOD.PERIODEND)
LEFT OUTER JOIN DL_PC_EXT.ET_pc_job ON 
DL_PC_EXT.ET_PC_JOB.ID = DL_PC_EXT.ET_PC_POLICYPERIOD.JOBID
LEFT OUTER JOIN  DL_PC_EXT.ET_PC_AUDITINFORMATION ON 
DL_PC_EXT.ET_PC_AUDITINFORMATION.ID = DL_PC_EXT.ET_PC_JOB.AUDITINFORMATIONID
    JOIN CTE_TRANSACTION_TYPE_CODE    ON (dl_pc_ext.et_PC_BOPTRANSACTION.BOPCost = CTE_TRANSACTION_TYPE_CODE.PC_BOPCOST_ID )
    LEFT OUTER JOIN CTE_TRANSACTION_CODE ON ( dl_pc_ext.et_PC_BOPTRANSACTION.ID = CTE_TRANSACTION_CODE.PC_JOB_ID)
    LEFT OUTER JOIN CTE_CHARGE_TYPECODE ON (dl_pc_ext.et_PC_BOPTRANSACTION.ID = CTE_CHARGE_TYPECODE.PC_BOPCOST_ID)
    LEFT OUTER JOIN CTE_CURRENCY_CODE ON(dl_pc_ext.et_PC_BOPTRANSACTION.ID =CTE_CURRENCY_CODE.PC_BOPTRANSACTION_ID)
    LEFT OUTER JOIN CTE_PCTL_TYPECODE    ON(dl_pc_ext.et_PC_BOPTRANSACTION.ID = CTE_PCTL_TYPECODE.PC_POLICYPERIOD_ID)
    LEFT OUTER JOIN dl_pc_ext.et_pc_POLICYTERM ON (dl_pc_ext.et_PC_BOPTRANSACTION.ID =dl_pc_ext.et_pc_POLICYTERM.ID )
    WHERE PCTL_TYPECODE IN ('Bound','AuditComplete');